version: '3.8'

services:
  merchant-yapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: merchant-yapp
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      # Environment variables can be passed here
      # They will override values in .env file
      # Example:
      # - VITE_ADMIN_CONFIG={"admins":[{"ens":"your-ens.eth"}]}
    networks:
      - merchant-network
    # For production, you might want to add healthcheck
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  merchant-network:
    driver: bridge 